name: CI

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Instala dependencias
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test unitarios
        run: npm test -- --coverage
      - name: Build de producción
        run: npm run build
      - name: Audit seguridad
        run: npm audit --audit-level=high
